@startuml
|Siswa|
start
:Mengakses Halaman Login;
:Input Email & Password;

|Sistem|
:Validasi Data Kredensial;
if (Valid?) then (Ya)
  :Tampilkan Dashboard Siswa;
else (Tidak)
  |Siswa|
  :Kembali ke Form Login;
  detach
endif

|Siswa|
:Pilih Menu Utama;
fork
  :Pilih Menu Materi & Tugas;
  |Sistem|
  :Tampilkan Daftar Materi & Tugas;
  |Siswa|
  :Membaca Materi & 
  Mengunggah Jawaban Tugas;
  |Sistem|
  :Simpan Jawaban ke Database;
fork again
  |Siswa|
  :Pilih Menu Rekap Akademik;
  |Sistem|
  :Ambil Data Kehadiran & Nilai;
  :Tampilkan Rekap Pribadi ke Siswa;
end merge

|Siswa|
:Klik Logout;
|Sistem|
:Menghapus Sesi (Sesi Berakhir);
stop
@enduml
