@startuml
|Guru|
start
:Mengakses Halaman Login;
:Input Email & Password;

|Sistem|
:Validasi Data Kredensial;
if (Valid?) then (Ya)
  :Tampilkan Dashboard Guru;
else (Tidak)
  |Guru|
  :Kembali ke Form Login;
  detach
endif

|Guru|
:Pilih Menu Utama;
fork
  :Pilih Menu Pembelajaran;
  |Sistem|
  :Tampilkan Daftar Kelas & Mapel;
  |Guru|
  :Upload Materi & Buat Tugas;
  |Sistem|
  :Simpan Data Pembelajaran;
fork again
  |Guru|
  :Pilih Menu Evaluasi Siswa;
  |Sistem|
  :Tampilkan Daftar Siswa;
  |Guru|
  :Input Absensi, Nilai, 
  dan Catatan Perilaku;
  |Sistem|
  :Update Rekap Siswa di Database;
end merge

|Guru|
:Klik Logout;
|Sistem|
:Menghapus Sesi (Sesi Berakhir);
stop
@enduml
