@startuml
|Orang Tua|
start
:Mengakses Halaman Login;
:Input Email & Password;

|Sistem|
:Validasi Data Kredensial;
if (Valid?) then (Ya)
  :Tampilkan Dashboard Orang Tua;
else (Tidak)
  |Orang Tua|
  :Kembali ke Form Login;
  detach
endif

|Orang Tua|
:Pilih Menu Pemantauan Anak;
|Sistem|
:Mencari Relasi Data Anak di Database;
:Ambil Data Akademik Anak 
(Absensi, Nilai, Perilaku);
:Tampilkan Detail Perkembangan Anak;

|Orang Tua|
:Melihat dan Memantau 
Informasi Akademik Anak;

:Klik Logout;
|Sistem|
:Menghapus Sesi (Sesi Berakhir);
stop
@enduml
