@startuml
left to right direction
skinparam packageStyle rectangle

actor "Admin / Tata Usaha" as admin
actor "Guru / Wali Kelas" as guru
actor "Siswa" as siswa
actor "Orang Tua" as ortu

rectangle "Learning Management System (LMS)" {
  usecase "Melakukan Login" as UC1
  usecase "Mengelola Data Master\n(Siswa, Guru, Kelas)" as UC2
  usecase "Mengelola KBM\n(Materi & Tugas)" as UC3
  usecase "Input Absensi, Nilai\n& Catat Perilaku" as UC4
  usecase "Mengakses Materi\n& Mengumpulkan Tugas" as UC5
  usecase "Melihat Rekap Kehadiran\n& Nilai Siswa" as UC6
  usecase "Memantau Akademik Anak\n(Kehadiran, Nilai, Perilaku)" as UC7
  usecase "Mencetak Laporan" as UC8
}

admin --> UC1
guru --> UC1
siswa --> UC1
ortu --> UC1

admin --> UC2
admin --> UC8

guru --> UC3
guru --> UC4
guru --> UC8

siswa --> UC5
siswa --> UC6

ortu --> UC7
@enduml
